image: maven:3.8.6-jdk-11

stages:
  - clean
  - build
  - package
  - deploy

variables:
  GL: "glpat-ySE_axhY1EmDgiFMn4sh"
  DB: "mongodb+srv://admin:learning@testcluster.9xdkqg5.mongodb.net/?retryWrites=true&w=majority&appName=TestCluster"

clean:
  stage: clean
  script:
    - mvn clean

build:
  stage: build
  script:
    - mvn javadoc:javadoc
    - mkdir -p src/main/resources/static/docs
    - cp -r target/site/apidocs/* src/main/resources/static/docs/

package:
  stage: package
  script:
    - mvn package
    - rm -rf src/main/resources/static/docs/

deploy:
  stage: deploy
  script:
    - java -jar target/MutexBot-1.0.jar || true
    - mvn clean
